### PR TITLE
Arabic Translation

### PR DESCRIPTION
**Pull request by ghost**
I've never worked with Arabic on computer aside from MS Word, so I'm not sure if this will work out well since Arabic is written from right to left.

### CODE REVIEW

**Comment by rurza** [comment]
Yeah, It's bigger change than other languages :)

**Comment by ghost** [comment]
Hey man is there any way you could send me another beta invitation, I stopped testing the app by mistake. Thanks!

**Comment by rurza** [comment]
sure :)

**Comment by rurza** [comment]
@AGreyPoupon It seems that you removed Arabic translation :(

**Comment by ghost** [comment]
I'm sorry I made a series of operations I must have deleted it by mistake, I'm on my iPhone now uploading first thing in the morning...

**Comment by rurza** [comment]
Okay!
Don't worry, I will restore it :)

**Pull request merged**
